import torch
import os
import matplotlib.pyplot as plt

def write_c_array(file_handle, name, tensor, cols, rows, pad_to_16=False):
    int8_array = torch.clamp(torch.round(tensor * 64.0), -128, 127).detach().numpy().astype(int)
    file_handle.write(f"tensor16x16_t {name} = {{{{\n")
    for r in range(16):
        row_data = [f"{int8_array[r, c]:4d}" if r < rows and c < cols else "   0" for c in range(16)]
        file_handle.write("    { " + ", ".join(row_data) + " }" + (",\n" if r < 15 else "\n"))
    file_handle.write("}};\n\n")

def write_dense_matrix_c(file_handle, name, tensor):
    int8_array = torch.clamp(torch.round(tensor * 64.0), -128, 127).detach().numpy().astype(int)
    rows, cols = int8_array.shape
    file_handle.write(f"const int8_t {name}[{rows}][{cols}] = {{\n")
    for r in range(rows):
        row_data = [f"{int8_array[r, c]:4d}" for c in range(cols)]
        file_handle.write("    { " + ", ".join(row_data) + " }" + (",\n" if r < rows - 1 else "\n"))
    file_handle.write("};\n\n")

def write_image_32x32_c(file_handle, name, tensor):
    int8_array = torch.clamp(torch.round(tensor * 64.0), -128, 127).detach().numpy().astype(int)
    file_handle.write(f"const int8_t {name}[32][32] = {{\n")
    for r in range(32):
        row_data = [f"{int8_array[r, c]:4d}" for c in range(32)]
        file_handle.write("    { " + ", ".join(row_data) + " }" + (",\n" if r < 31 else "\n"))
    file_handle.write("};\n\n")

def write_anchor_vector_c(file_handle, name, tensor):
    int8_array = torch.clamp(torch.round(tensor * 64.0), -128, 127).detach().numpy().astype(int)
    row_data = [f"{int8_array[c]:4d}" for c in range(32)]
    # FIXED BUG: Changed [8] to [32] to match the Quadrant Pooling signature length
    file_handle.write(f"const int8_t {name}[32] = {{ " + ", ".join(row_data) + " };\n\n")

def export_firmware(model, test_img, test_lbl, anchors, optimal_threshold):
    export_dir = "exported_c"
    os.makedirs(export_dir, exist_ok=True)
    
    with open(f"{export_dir}/weights.h", "w") as f:
        f.write("// AUTOGENERATED 32x32 CIMMETRY WEIGHTS & ANCHORS\n")
        f.write(f"// IMPORTANT: Nios II Distance Threshold: {optimal_threshold:.2f}\n\n")
        f.write("#ifndef WEIGHTS_H\n#define WEIGHTS_H\n\n")
        
        write_c_array(f, "W_conv", model.W_conv, 16, 16)
        write_c_array(f, "W_linear", model.W_linear, 8, 16, pad_to_16=True)
        
        f.write("// AUTHORIZED PERSONNEL ANCHORS (32-bytes each)\n")
        # Dynamically matches the number of anchors passed from train.py
        for i in range(len(anchors)):
            write_anchor_vector_c(f, f"Anchor_Person_{i}", anchors[i])
            
        f.write("#endif\n")

    with open(f"{export_dir}/test_images.h", "w") as f:
        f.write("// AUTOGENERATED 32x32 TEST IMAGES (6 Images total)\n")
        f.write("#ifndef TEST_IMAGES_H\n#define TEST_IMAGES_H\n\n")
        counts = {0: 0, 1: 0, 2: 0} 
        
        for i in range(len(test_img)):
            lbl = test_lbl[i].item()
            # We only want to export test images for our 3 authorized users
            if lbl in counts:
                idx = counts[lbl]
                counts[lbl] += 1
                
                img_tensor = test_img[i].view(32, 32)
                name = f"Person_{lbl}_Test_{idx}"
                
                write_image_32x32_c(f, name, img_tensor)
                png_path = os.path.join(export_dir, f"{name}.png")
                plt.imsave(png_path, img_tensor.detach().numpy(), cmap='gray', vmin=-1.0, vmax=1.0)

        f.write("#endif\n")
    print(f"[*] Firmware arrays, Anchors, and PNGs saved to {export_dir}/")